name: Build Python 3

on:
  push:
    branches: ['main']
    paths:
      - '.github/workflows/build_python3.yml'

  # Run manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/variantxyz/gcc-powerpc-apple-darwin8:build-gcc-14.2-macosxsdk10.4u

    steps:
      - name: Checkout cpython
        uses: actions/checkout@v4
        with:
          repository: variantxyz/cpython.git
          ref: v3.12.8+powerpc-apple-darwin8
          path: 'cpython'

      - name: Install prerequisites
        run: |
          apt-get update
          apt-get install -y python3-dev

      - name: Build host
        run: |
          mkdir -p host_build
          cd host_build
          CC=clang CXX=clang++ ../cpython/configure 
          make -j2
          make install -j

      - name: Build target
        run: |
          mkdir -p $GITHUB_WORKSPACE/deploy
          mkdir -p target_build
          cd target_build
          echo "" > config.site-powerpc-apple-darwin8
          echo "ac_cv_file__dev_ptmx=no" >> config.site-powerpc-apple-darwin8
          echo "ac_cv_file__dev_ptc=no" >> config.site-powerpc-apple-darwin8
          echo "ac_cv_enable_implicit_function_declaration_error=no" >> config.site-powerpc-apple-darwin8
          echo "ac_cv_disable_int_conversion_warning=yes" >> config.site-powerpc-apple-darwin8
          PATH=/usr/local/powerpc-apple-darwin8/bin:$PATH MACOSX_DEPLOYMENT_TARGET=10.4 MACHDEP=Darwin CONFIG_SITE=./config.site-powerpc-apple-darwin8 ../cpython/configure CC="powerpc-apple-darwin8-gcc" CXX="powerpc-apple-darwin8-g++" LD="powerpc-apple-darwin8-gcc" BLDSHARED="powerpc-apple-darwin8-gcc -Wl,-undefined,suppress -Wl,-flat_namespace -shared" LDSHARED="powerpc-apple-darwin8-gcc" AS="powerpc-apple-darwin8-as" AR="powerpc-apple-darwin8-ar" RANLIB="powerpc-apple-darwin8-ranlib" CFLAGS="-mmacosx-version-min=10.4 --include "sys/types.h" -include "sys/socket.h" -include "sys/uio.h" -include "sys/resource.h" -include "fcntl.h" -Wno-error=implicit-function-declaration -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -DO_NOFOLLOW=0" LDFLAGS="-mmacosx-version-min=10.4 -static-libstdc++ -static-libgcc" --disable-ipv6 --prefix=$GITHUB_WORKSPACE/deploy --host=powerpc-apple-darwin8 --build=$(gcc -dumpmachine) --with-build-python=../host_build/python --with-ensurepip=no --without-readline --enable-optimizations
          PATH=/usr/local/powerpc-apple-darwin8/bin:$PATH make -j2
          PATH=/usr/local/powerpc-apple-darwin8/bin:$PATH make install -j

      - name: 'Archive'
        uses: actions/upload-artifact@v4
        with:
          name: cpython
          path: deploy
          retention-days: 1