name: Build RGBDS Toolchain

on:
  push:
    branches: ['main']
    paths:
      - '.github/workflows/build_rgbds.yml'

  # Run manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/variantxyz/gcc-powerpc-apple-darwin8:main

    steps:
      - name: Checkout libpng
        uses: actions/checkout@v6
        with:
          repository: pnggroup/libpng.git
          ref: f753baae52e1f0fd5451c25de8f8361ec5aea95f
          path: 'libpng'

      - name: Build libpng
        run: |
          mkdir -p build_libpng
          cd build_libpng
          LDFLAGS="-static-libstdc++ -static-libgcc" CXX=powerpc-apple-darwin8-g++ CC=powerpc-apple-darwin8-g++ ../libpng/configure --prefix=/usr/local/powerpc-apple-darwin8 --host=powerpc-apple-darwin8
          make -j
          make install -j

      - name: Checkout rgbds
        uses: actions/checkout@v2
        with:
          repository: gbdev/rgbds.git
          ref: v0.9.0
          path: 'rgbds'

      - name: Install prerequisites for rgbds
        run: |
          apt-get update -q
          apt-get install -y bison

      - name: Build rgbds
        run: |
          mkdir -p deploy
          cd rgbds
          PATH=/usr/local/powerpc-apple-darwin8/bin/:$PATH make install -j LDFLAGS="-static-libstdc++ -static-libgcc" PNGCFLAGS="" PNGLDFLAGS="-lpng" PNGLDLIBS="" CXX=powerpc-apple-darwin8-g++ CC=powerpc-apple-darwin8-gcc CXXFLAGS="-D__STDC_FORMAT_MACROS" PREFIX=../deploy

      - name: 'Archive'
        uses: actions/upload-artifact@v4
        with:
          name: rgbds
          path: deploy
          retention-days: 1