name: Build SameBoy

on:
  push:
    branches: ['main']
    paths:
      - '.github/workflows/build_sameboy.yml'
      - '.github/workflows/build_sdl2.yml'

  # Run manually
  workflow_dispatch:

  workflow_call:

jobs:
  sdl2:
    uses: ./.github/workflows/build_sdl2.yml

  sameboy:
    runs-on: ubuntu-latest
    container: ghcr.io/variantxyz/gcc-powerpc-apple-darwin8:build-gcc-14.2-macosxsdk10.4u
    needs: [sdl2]

    steps:
      - name: Checkout Addendums
        uses: actions/checkout@v4
        with:
          repository: VariantXYZ/MacOSX10.4u_Addendum
          path: MacOSX10.4u_Addendum

      - name: Create Deployment Directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/deploy

      - uses: actions/download-artifact@v4
        with:
          path: deploy
          merge-multiple: true

      - name: Install RGBDS prerequisites
        run: |
          apt-get update && apt-get install -y bison libpng-dev pkg-config

      - name: Checkout rgbds
        uses: actions/checkout@v4
        with:
          repository: gbdev/rgbds.git
          ref: v0.9.0
          path: 'rgbds'

      - name: Build and install RGBDS
        run: |
          cd rgbds
          make -j
          make install

      - name: Checkout SameBoy
        uses: actions/checkout@v4
        with:
          repository: VariantXYZ/SameBoy
          ref: tiger/master
          path: 'sameboy'

      # (Just make the platform 'Unix' to avoid dealing with 10.9-isms)
      - name: Build SameBoy for target
        run: |
          cd sameboy

          PKG_CONFIG_PATH=$GITHUB_WORKSPACE/deploy/lib/pkgconfig MACOSX_DEPLOYMENT_TARGET=10.4 CC="powerpc-apple-darwin8-gcc" CXX="powerpc-apple-darwin8-g++" LD="powerpc-apple-darwin8-gcc" CFLAGS="-Wno-error=unused-function -Wno-error=unused-variable -I$(realpath ..)/MacOSX10.4u_Addendum -include stdlib_addendum.h -I$GITHUB_WORKSPACE/deploy/include" LDFLAGS="-L$GITHUB_WORKSPACE/deploy/lib" PREFIX="$GITHUB_WORKSPACE/deploy" make PLATFORM=Unix GL_CFLAGS="-framework OpenGL" GL_LDFLAGS="-framework OpenGL" sdl


      - name: 'Archive'
        uses: actions/upload-artifact@v4
        with:
          name: sameboy
          path: sameboy/build/bin
          retention-days: 1
          overwrite: true