name: Build OpenSSH

on:
  push:
    branches: ['main']
    paths:
      - '.github/workflows/build_openssh.yml'
      - '.github/workflows/build_openssl.yml'
      - '.github/workflows/build_zlib.yml'

  # Run manually
  workflow_dispatch:

  workflow_call:

jobs:
  zlib:
    uses: ./.github/workflows/build_zlib.yml
  
  openssl:
    uses: ./.github/workflows/build_openssl.yml

  build:
    runs-on: ubuntu-latest
    container: ghcr.io/variantxyz/gcc-powerpc-apple-darwin8:build-gcc-14.2-macosxsdk10.4u
    needs:
      - openssl
      - zlib # Included within openssl

    steps:
      - name: Checkout Addendums
        uses: actions/checkout@v4
        with:
          repository: VariantXYZ/MacOSX10.4u_Addendum
          path: MacOSX10.4u_Addendum

      - name: Create Deployment Directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/deploy

      - uses: actions/download-artifact@v4
        with:
          path: deploy
          merge-multiple: true

      - name: Checkout openssh
        uses: actions/checkout@v4
        with:
          repository: openssh/openssh-portable
          ref: V_9_9_P1
          path: 'openssh'

      - name: Build openssh for target
        run: |
          cd openssh
          autoreconf -fi
          echo "" > config.site-powerpc-apple-darwin8
          echo "ac_cv_c_undeclared_builtin_options=''" >> config.site-powerpc-apple-darwin8
          PATH=/usr/local/powerpc-apple-darwin8/bin:$PATH ./configure CONFIG_SITE=./config.site-powerpc-apple-darwin8 --prefix=$GITHUB_WORKSPACE/deploy CC="powerpc-apple-darwin8-gcc" CXX="powerpc-apple-darwin8-g++" LD="powerpc-apple-darwin8-gcc" CPPFLAGS="-I$GITHUB_WORKSPACE/deploy/include" CFLAGS="-Wno-error=implicit-function-declaration -Wno-error=int-conversion -Wno-error=incompatible-pointer-types" LDFLAGS="-L$GITHUB_WORKSPACE/deploy/lib" --with-zlib="$GITHUB_WORKSPACE/deploy" --with-ssl-dir="$GITHUB_WORKSPACE/deploy" --host=powerpc-apple-darwin8 --build=$(gcc -dumpmachine)
          PATH=/usr/local/powerpc-apple-darwin8/bin/:$PATH make -j4
          PATH=/usr/local/powerpc-apple-darwin8/bin/:$PATH make install-files -j
          PATH=/usr/local/powerpc-apple-darwin8/bin/:$PATH make install-sysconf -j

      - name: 'Archive'
        uses: actions/upload-artifact@v4
        with:
          name: openssh
          path: deploy
          retention-days: 1
          overwrite: true