name: Build Git

on:
  push:
    branches: ['main']
    paths:
      - '.github/workflows/build_iconv.yml'

  # Run manually
  workflow_dispatch:

  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/variantxyz/gcc-powerpc-apple-darwin8:build-gcc-14.2-macosxsdk10.4u

    steps:
      - name: Checkout Addendums
        uses: actions/checkout@v4
        with:
          repository: VariantXYZ/MacOSX10.4u_Addendum
          path: MacOSX10.4u_Addendum

      - name: Create Deployment Directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/deploy

      # checkout doesn't seem to support external repositories...
      - name: Checkout libiconv
        run: |
          git clone https://git.savannah.gnu.org/git/libiconv.git --depth 1 --branch v1.18 libiconv
          cd libiconv
          git submodule update --init --recursive

      - name: Install libiconv prerequisites
        run: |
          apt-get update && apt-get install -y gperf groff

      - name: Build libiconv for target
        run: |
          cd libiconv
          ln -s /usr/bin/aclocal /usr/bin/aclocal-1.17 || echo "aclocal exists"
          ln -s /usr/bin/automake /usr/bin/automake-1.17 || echo "automake exists"
          ./gitsub.sh pull
          ./autogen.sh
          echo "" > config.site-powerpc-apple-darwin8
          PATH=/usr/local/powerpc-apple-darwin8/bin/:$PATH ./configure CONFIG_SITE=./config.site-powerpc-apple-darwin8 --prefix=$GITHUB_WORKSPACE/deploy CC="powerpc-apple-darwin8-gcc" CXX="powerpc-apple-darwin8-g++" LD="powerpc-apple-darwin8-gcc" CFLAGS="-Wno-error=implicit-function-declaration -Wno-error=int-conversion -Wno-error=incompatible-pointer-types" --host=powerpc-apple-darwin8 --build=$(gcc -dumpmachine) --enable-static
          PATH=/usr/local/powerpc-apple-darwin8/bin/:$PATH make -j4
          PATH=/usr/local/powerpc-apple-darwin8/bin/:$PATH make install -j

      - name: 'Archive'
        uses: actions/upload-artifact@v4
        with:
          name: iconv
          path: deploy
          retention-days: 1
          overwrite: true