name: Build Curl

on:
  push:
    branches: ['main']
    paths:
      - '.github/workflows/build_curl.yml'
      - '.github/workflows/build_openssl.yml'
      - '.github/workflows/build_zlib.yml'

  # Run manually
  workflow_dispatch:

  workflow_call:

jobs:
  # zlib:
  #  uses: ./.github/workflows/build_zlib.yml
  
  openssl:
    uses: ./.github/workflows/build_openssl.yml

  build:
    runs-on: ubuntu-latest
    container: ghcr.io/variantxyz/gcc-powerpc-apple-darwin8:build-gcc-14.2-macosxsdk10.4u
    needs:
      - openssl
      #- zlib # Included within openssl

    steps:
      - name: Checkout Addendums
        uses: actions/checkout@v4
        with:
          repository: VariantXYZ/MacOSX10.4u_Addendum
          path: MacOSX10.4u_Addendum

      - name: Create Deployment Directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/deploy

      - uses: actions/download-artifact@v4
        with:
          path: deploy
          merge-multiple: true

      - name: Checkout curl
        uses: actions/checkout@v4
        with:
          repository: curl/curl
          ref: curl-8_11_1
          path: 'curl'

      - name: Build curl for target
        run: |
          mkdir -p $GITHUB_WORKSPACE/deploy
          cd curl
          autoreconf -fi
          echo "" > config.site-powerpc-apple-darwin8
          echo "ac_cv_c_undeclared_builtin_options=''" >> config.site-powerpc-apple-darwin8
          PATH=/usr/local/powerpc-apple-darwin8/bin/:$PATH ./configure CONFIG_SITE=./config.site-powerpc-apple-darwin8 --prefix=$GITHUB_WORKSPACE/deploy CC="powerpc-apple-darwin8-gcc -v" CXX="powerpc-apple-darwin8-g++" LD="powerpc-apple-darwin8-gcc" CPPFLAGS="-I$GITHUB_WORKSPACE/deploy/include -I$(realpath ..)/MacOSX10.4u_Addendum -include stdlib_addendum.h" CFLAGS="-Wno-error=implicit-function-declaration -Wno-error=int-conversion -Wno-error=incompatible-pointer-types" LDFLAGS="-L$GITHUB_WORKSPACE/deploy/lib" --host=powerpc-apple-darwin8 --with-openssl --without-libpsl --without-libgsasl
          PATH=/usr/local/powerpc-apple-darwin8/bin/:$PATH make -j4
          PATH=/usr/local/powerpc-apple-darwin8/bin/:$PATH make install -j

      - name: 'Archive'
        uses: actions/upload-artifact@v4
        with:
          name: curl
          path: deploy
          retention-days: 1