name: Build Git

on:
  push:
    branches: ['main']
    paths:
      - '.github/workflows/build_git.yml'
      - '.github/workflows/build_curl.yml'
      - '.github/workflows/build_openssl.yml'
      - '.github/workflows/build_zlib.yml'
      - '.github/workflows/build_iconv.yml'

  # Run manually
  workflow_dispatch:

  workflow_call:

jobs:
  zlib:
    uses: ./.github/workflows/build_zlib.yml
  
  openssl:
    uses: ./.github/workflows/build_openssl.yml

  curl:
    uses: ./.github/workflows/build_curl.yml

  iconv:
    uses: ./.github/workflows/build_iconv.yml

  git:
    runs-on: ubuntu-latest
    container: ghcr.io/variantxyz/gcc-powerpc-apple-darwin8:build-gcc-14.2-macosxsdk10.4u
    needs:
      - curl
      - openssl
      - zlib
      - iconv

    steps:
      - name: Checkout Addendums
        uses: actions/checkout@v4
        with:
          repository: VariantXYZ/MacOSX10.4u_Addendum
          path: MacOSX10.4u_Addendum

      - name: Create Deployment Directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/deploy

      - uses: actions/download-artifact@v4
        with:
          path: deploy
          merge-multiple: true

      - name: Checkout git
        uses: actions/checkout@v4
        with:
          repository: git/git.git
          ref: v2.48.1
          submodules: 'true'
          path: 'git'

      - name: Build git for target
        run: |
          cd git
          make configure
          echo "" > config.site-powerpc-apple-darwin8
          echo "ac_cv_fread_reads_directories=true" >> config.site-powerpc-apple-darwin8
          echo "ac_cv_snprintf_returns_bogus=false" >> config.site-powerpc-apple-darwin8
          echo "ac_cv_iconv_omits_bom=false" >> config.site-powerpc-apple-darwin8
          PATH=/usr/local/powerpc-apple-darwin8/bin/:$PATH ./configure CONFIG_SITE=./config.site-powerpc-apple-darwin8 --prefix=$GITHUB_WORKSPACE/deploy NO_PERL=1 CC="powerpc-apple-darwin8-gcc" CXX="powerpc-apple-darwin8-g++" LD="powerpc-apple-darwin8-gcc" CFLAGS="-DSHA1DC_BIGENDIAN -Wno-error=implicit-function-declaration -Wno-error=int-conversion -Wno-error=incompatible-pointer-types -I$GITHUB_WORKSPACE/deploy/include -I$(realpath ..)/MacOSX10.4u_Addendum -include stdlib_addendum.h" LDFLAGS="-L$GITHUB_WORKSPACE/deploy/lib" --host=powerpc-apple-darwin8 --without-tcltk --with-curl --with-openssl --with-iconv
          PATH=/usr/local/powerpc-apple-darwin8/bin/:$PATH make install uname_S=Darwin uname_R=8.11 CURLDIR=$GITHUB_WORKSPACE/deploy CURL_LDFLAGS="-lcurl" FSMONITOR_DAEMON_BACKEND="" USE_ENHANCED_BASIC_REGULAR_EXPRESSIONS="" -j4

      - name: 'Archive'
        uses: actions/upload-artifact@v4
        with:
          name: git
          path: deploy
          retention-days: 1
          overwrite: true